#! /bin/sh

sxhkd &
setxkbmap -layout us,ru -option grp:alt_shift_toggle &
$HOME/.config/polybar/launch.sh &
#polybar example &
picom &
#$HOME/.config/lemonbar/panel &
feh --bg-scale $HOME/Изображения/377.png &

bspc monitor eDP-1 -d 1 2 3
bspc monitor HDMI-1 -d 4 5 6 7 8

bspc config normal_border_color "#44475a"
bspc config presel_feedback_color "#6272a4"
bspc config active_border_color "#f61d2b"
bspc config focused_border_color "#f61d2b"

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

